---
title: "p8105_hw5_ga2612"
author: "Lupe Antonio"
date: "11/12/2023"
output: 
  github_document:
    toc: TRUE
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Problem 1

```{r, message = FALSE}
#loading data
homicide_data <- read_csv('data_hw5/homicide_data.csv')
```







## Problem 2


Make a spaghetti plot showing observations on each subject over time, and comment on differences between groups.



```{r, message=FALSE}
#loading data
file_names <- list.files(path = 'data_hw5/p2_data') %>%
  as_tibble() %>%
  rename(file_name = value) %>%
  #iterating over file names, reading file, and create new variable in df
  mutate(
    data = map(str_c('./data_hw5/p2_data/', file_name), read_csv)) %>%
  unnest(cols = data) %>%
  pivot_longer(week_1:week_8,
               names_to = 'week',
               values_to = 'value') %>%
  mutate(
    #creating arm variable for either control or experimental
    arm = case_when(
      str_detect(file_name, 'con') ~ 'control',
      TRUE ~ 'experimental'),
    
    #creating subject id variable
    id = as.numeric(str_sub(file_name, start = 5, end = 6)),
    
    #updating week to numeric
    week = as.numeric(str_sub(week, start = 6, end = 6)))
  
```


```{r}
#creating plot
file_names %>%
  ggplot(aes(x = week, y = value, color = arm, group = interaction(id, arm))) +
  geom_line() +
  ggtitle('Observations per subjects between week 1 and 8')
```


